### ISSUE TITLE
Change index-pattern when run logstash

### ISSUE THREAD

**Issue by autorun1918** [stormshield/stormshield-ELK#1]
Hello,
I have little problem.
When i import index-pattern i see 291 field.
![image](https://user-images.githubusercontent.com/47558738/52628514-21f3d980-2eb8-11e9-9dbf-6e59894699c5.png)
When i run logstash, index refresh and replace fields, and change types
![image](https://user-images.githubusercontent.com/47558738/52628758-96c71380-2eb8-11e9-8748-9a26c6f1ea5e.png)

**Comment by nabilbendafi** [comment]
Make sure you have data from SNS products. In other word, that indice(s) `stormshield-sns-*` is(are) not empty before trying to refresh

**Comment by autorun1918** [comment]
Data before refreshing aggregates below the output settings of the print screen
Im not refresh index, i refresh page only.


![image](https://user-images.githubusercontent.com/47558738/52642612-a2780180-2edb-11e9-8a71-41c74b502b61.png)
