### ISSUE TITLE
Update to ELK 6.*

### ISSUE THREAD

**Issue by autorun1918** [stormshield/stormshield-ELK#2]

**Comment by nabilbendafi** [comment]
In our roadmap

**Comment by Seculin** [comment]
Hello team, do you know when it will ben possible?

**Comment by autorun1918** [comment]
What are the works on the update?

**Comment by autorun1918** [comment]
Is the update planned for this year?

**Comment by thomasescure** [comment]
Hi! The upgrade will be included in the next SVC release, planned for september 2019.

**Comment by autorun1918** [comment]
What is the progress of the work?

**Comment by thomasescure** [comment]
Hi autorun ! The development of SVC 1.5 is over and the release is planned for the 16th of October 2019.  The SVC gitHub repository will be also updated for this date.

**Comment by autorun1918** [comment]
Hello,
How are the work going?

**Comment by thomasescure** [comment]
Hi autorun1918  ! The repo has been updated and is now compliant with ELK 6.8.2.
